exports.CstmrSchema = { 
                                    "fields":  [ {"nm": "agnt_id","type":"bigint(20)","required":"false"},
									 {"nm": "cstmr_fst_nm","type":"varchar(45)","required":"true"},
									 {"nm": "cstmr_mdl_nm","type":"varchar(45)","required":"false"},
									 {"nm": "cstmr_lst_nm","type":"varchar(45)","required":"true"},
									 {"nm": "cstmr_mble_nu","type":"int(11)","required":"true"},
									 {"nm": "cstmr_emle_tx","type":"varchar(120)","required":"false"},
									 {"nm": "gndr_id","type":"bigint(20)","required":"true"},
									 {"nm": "adhr_nu","type":"bigint(20)","required":"true"},
									 {"nm": "pan_nu","type":"varchar(45)","required":"false"},
									 {"nm": "cntct_prsn_nm","type":"varchar(45)","required":"true"},
									 {"nm": "cntct_prsn_mble_nu","type":"int(11)","required":"true"},
									 {"nm": "cntct_prsn_emle_tx","type":"varchar(120)","required":"false"},
									 {"nm": "cntct_prsn_dsgn_id","type":"bigint(20)","required":"false"},
									 {"nm": "blng_frqny_id","type":"bigint(20)","required":"true"},
									 {"nm": "actvtn_dt","type":"date","required":"true"},
									 {"nm": "instl_hse_nu","type":"varchar(45)","required":"true"},
									 {"nm": "instl_strte_tx","type":"varchar(45)","required":"true"},
									 {"nm": "instl_lclty_tx","type":"varchar(45)","required":"true"},
									 {"nm": "instl_mndle_id","type":"bigint(20)","required":"true"},
									 {"nm": "instl_cty_id","type":"bigint(20)","required":"true"},
									 {"nm": "instl_dstrt_id","type":"bigint(20)","required":"true"},
									 {"nm": "instl_ste_id","type":"bigint(20)","required":"true"},
									 {"nm": "instl_pn_cd","type":"int(11)","required":"true"},
									 {"nm": "instl_lnd_nu","type":"int(20)","required":"false"},
									 {"nm": "instl_lat","type":"decimal(18,12)","required":"false"},
									 {"nm": "instl_lng","type":"decimal(18,12)","required":"false"},
									 {"nm": "blng_hse_nu","type":"varchar(45)","required":"true"},
									 {"nm": "blng_strte_tx","type":"varchar(45)","required":"true"},
									 {"nm": "blng_lclty_tx","type":"varchar(45)","required":"true"},
									 {"nm": "blng_mndle_id","type":"bigint(20)","required":"true"},
									 {"nm": "blng_cty_id","type":"bigint(20)","required":"true"},
									 {"nm": "blng_dstrt_id","type":"bigint(20)","required":"true"},
									 {"nm": "blng_ste_id","type":"bigint(20)","required":"true"},
									 {"nm": "blng_pn_cd","type":"int(11)","required":"true"},
									 {"nm": "blng_lnd_nu","type":"int(20)","required":"false"},
									 {"nm": "blng_lat","type":"decimal(18,12)","required":"false"},
									 {"nm": "blng_lng","type":"decimal(18,12)","required":"false"},
									 {"nm": "crte_usr_id","type":"bigint(11)","required":"false"},
									 {"nm": "updte_usr_id","type":"bigint(11)","required":"false"},
									],
                                    "required": ["cstmr_id,cstmr_fst_nm,cstmr_lst_nm,cstmr_mble_nu,gndr_id,adhr_nu,cntct_prsn_nm,cntct_prsn_mble_nu,blng_frqny_id,actvtn_dt,instl_hse_nu,instl_strte_tx,instl_lclty_tx,instl_mndle_id,instl_cty_id,instl_dstrt_id,instl_ste_id,instl_pn_cd,blng_hse_nu,blng_strte_tx,blng_lclty_tx,blng_mndle_id,blng_cty_id,blng_dstrt_id,blng_ste_id,blng_pn_cd"],
                                    "keys": ["cstmr_id"]
                                 };