exports.EntrpeCstmrSchema = { 
   "fields":  [ {"nm": "entrpe_cstmr_nm","type":"varchar(120)","required":"true"},
{"nm": "entrpe_cstmr_cd","type":"varchar(120)","required":"true"},
{"nm": "entrpe_type_id","type":"bigint(20)","required":"true"},
{"nm": "entpnr_sub_type_id","type":"bigint(20)","required":"true"},
{"nm": "entpnr_org_nm","type":"varchar(120)","required":"true"},
{"nm": "rgstn_vat_tan_no","type":"varchar(45)","required":"true"},
{"nm": "incrn_dt","type":"date","required":"true"},
{"nm": "adhr_nu","type":"bigint(20)","required":"true"},
{"nm" : "adhr_img_url_tx", "type":"varchar(255)","required":"false"},
{"nm": "pan_nu","type":"varchar(45)","required":"true"},
{"nm" : "pan_img_url_tx", "type":"varchar(255)","required":"false"},
{"nm": "gst_nu","type":"varchar(45)","required":"false"},
{"nm" : "gst_img_url_tx", "type":"varchar(255)","required":"false"},
{"nm": "cntct_prsn_nm","type":"varchar(45)","required":"true"},
{"nm": "cntct_prsn_mble_nu","type":"tinyint(11)","required":"true"},
{"nm": "cntct_prsn_emle_tx","type":"varchar(120)","required":"true"},
{"nm": "cntct_prsn_dsgn_id","type":"bigint(20)","required":"true"},
{"nm": "blng_frqny_id","type":"bigint(20)","required":"true"},
{"nm": "actvtn_dt","type":"date","required":"true"},
{"nm": "instl_hse_nu","type":"varchar(45)","required":"true"},
{"nm": "instl_bldng_tx","type":"varchar(45)","required":"true"},
{"nm": "instl_strte_tx","type":"varchar(45)","required":"true"},
{"nm": "instl_lclty_tx","type":"varchar(45)","required":"true"},
{"nm": "instl_mndle_id","type":"bigint(20)","required":"true"},
{"nm": "instl_cty_id","type":"bigint(20)","required":"true"},
{"nm": "instl_dstrt_id","type":"bigint(20)","required":"true"},
{"nm": "instl_ste_id","type":"bigint(20)","required":"true"},
{"nm": "instl_pn_cd","type":"int(11)","required":"true"},
{"nm": "instl_fax_nu","type":"varchar(20)","required":"false"},
{"nm": "instl_lnd_nu","type":"int(20)","required":"false"},
{"nm": "instl_lat","type":"decimal(18,12)","required":"false"},
{"nm": "instl_lng","type":"decimal(18,12)","required":"false"},
{"nm": "blng_hse_nu","type":"varchar(45)","required":"true"},
{"nm": "blng_bldng_tx","type":"varchar(45)","required":"false"},
{"nm": "blng_strte_tx","type":"varchar(45)","required":"true"},
{"nm": "blng_lclty_tx","type":"varchar(45)","required":"true"},
{"nm": "blng_mndle_id","type":"bigint(20)","required":"true"},
{"nm": "blng_cty_id","type":"bigint(20)","required":"true"},
{"nm": "blng_dstrt_id","type":"bigint(20)","required":"true"},
{"nm": "blng_ste_id","type":"bigint(20)","required":"true"},
{"nm": "blng_pn_cd","type":"int(11)","required":"true"},
{"nm": "blng_fax_nu","type":"varchar(20)","required":"false"},
{"nm": "blng_lnd_nu","type":"int(20)","required":"false"},
{"nm": "blng_lat","type":"decimal(18,12)","required":"false"},
{"nm": "blng_lng","type":"decimal(18,12)","required":"false"},
{"nm": "chckd_ind","type":"int(11)","required":"false"},
{"nm": "crte_usr_id","type":"bigint(11)","required":"false"},
{"nm": "updte_usr_id","type":"bigint(11)","required":"false"},
],
   "required": ["entrpe_cstmr_id,entrpe_cstmr_nm,entrpe_cstmr_cd,entrpe_type_id,entpnr_sub_type_id,entpnr_org_nm,rgstn_vat_tan_no,incrn_dt,adhr_nu,pan_nu,cntct_prsn_nm,cntct_prsn_mble_nu,cntct_prsn_emle_tx,cntct_prsn_dsgn_id,blng_frqny_id,actvtn_dt,instl_hse_nu,instl_bldng_tx,instl_strte_tx,instl_lclty_tx,instl_mndle_id,instl_cty_id,instl_dstrt_id,instl_ste_id,instl_pn_cd,blng_hse_nu,blng_strte_tx,blng_lclty_tx,blng_mndle_id,blng_cty_id,blng_dstrt_id,blng_ste_id,blng_pn_cd"],
   "keys": ["entrpe_cstmr_id"]
};